#!/bin/bash
echo "Setup container environment variables."
export CONFIG_SERVICE_PASSWORD="123"
export NOTIFICATION_SERVICE_PASSWORD="123"
export STATISTICS_SERVICE_PASSWORD="123"
export ACCOUNT_SERVICE_PASSWORD="123"
export MONGODB_PASSWORD="123"
export CONFIG_SERVICE_SERVER=`docker-machine ip`
printenv --null CONFIG_SERVICE_PASSWORD NOTIFICATION_SERVICE_PASSWORD STATISTICS_SERVICE_PASSWORD ACCOUNT_SERVICE_PASSWORD MONGODB_PASSWORD CONFIG_SERVICE_SERVER
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up